In [2]:
# Zach Quinn
# DSC 550 
# 2 August 2020
# File Name: DSC_550_Week8
# File Description: A file that creates vectors to solve assigned problems.
# File Function: Uses Pandas, numpy, scipy and linalg functions 
# to solve assigned problems and excercise 
# from Mining with Massive Data sets.

In [3]:
import pandas as pd
import numpy as np
from scipy.spatial.distance import cdist
import scipy.linalg as lalg
from scipy.linalg import svd

# Excercise 1a

In [4]:
# Create dict with keys of column names and values of row values.
rating_info = { 'Rater': ['A', 'B', 'C'],
                'M': [1, 2, 5],
                'N': [2, 3, 5],
                'P': [3, 2, 5],
                'Q': [4 , 5, 3],
                'R': [5, 3, 2]
              }

In [5]:
# Convert the dictionary to a Pandas data frame.
rating_table = pd.DataFrame(rating_info)

In [6]:
rating_table.head()

Rater  M  N  P  Q  R
0     A  1  2  3  4  5
1     B  2  3  2  5  3
2     C  5  5  5  3  2

In [7]:
# Delete the 'rater column.'
del rating_table['Rater']

In [8]:
rating_table.head()

M  N  P  Q  R
0  1  2  3  4  5
1  2  3  2  5  3
2  5  5  5  3  2

In [9]:
# Take the mean of first three rows only. 
rating_table.mean(axis=1)

0    3.0
1    3.0
2    4.0
dtype: float64

In [10]:
# Subtract mean of each column from the value of corresponding column. 
rating_table_avg_from_val = rating_table.sub(rating_table.mean(axis=1),axis=0)

In [11]:
rating_table_avg_from_val.head()

M    N    P    Q    R
0 -2.0 -1.0  0.0  1.0  2.0
1 -1.0  0.0 -1.0  2.0  0.0
2  1.0  1.0  1.0 -1.0 -2.0

In [12]:
# Calculate the mean of the table. 
rating_table_avg_from_val.mean()

M   -0.666667
N    0.000000
P    0.000000
Q    0.666667
R    0.000000
dtype: float64

In [13]:
rating_table_avg_from_val = rating_table_avg_from_val.sub(rating_table_avg_from_val.mean(axis=0),axis=1)

In [14]:
rating_table_avg_from_val

M    N    P         Q    R
0 -1.333333 -1.0  0.0  0.333333  2.0
1 -0.333333  0.0 -1.0  1.333333  0.0
2  1.666667  1.0  1.0 -1.666667 -2.0

# Excercise 1b.

In [15]:
# Define function to find cosine distance similarity. 
def calculate_cos_dist(x,y):
    return np.dot(x,y) / (np.sqrt(np.sum(np.power(x,2))) * np.sqrt(np.sum(np.power(y,2))))

In [16]:
# defining function to calculate weighted cosine distance. 
# Function takes parameters col_index and alpha_val.
def calculate_weighted_cos_dist(col_index,alpha_val):
# Initiate list of lists. 
    p=[[1,0,1,0,1,2],[1,1,0,0,1,6],[0,1,0,1,0,2]]
# Convert to data frame. 
    o=pd.DataFrame(p,columns=None)
# Transform the o matrix.
    m=o.T
# Add columns for m matrix.
    m.columns=['A','B','C']
# Transform m. 
    data=m.T
# Multiply data[col_index] times alpha_val.
    data[col_index]=data[col_index] * alpha_val
# Apply function to indexed value. 
    print(calculate_cos_dist(data.iloc[0], data.iloc[1]))
    print(calculate_cos_dist(data.iloc[1], data.iloc[2]))
    print(calculate_cos_dist(data.iloc[0], data.iloc[2]))
# Format output.
    print('----'*30)
# Print text and final output. 
    print("Weighted value:")
    print(data[col_index])

In [17]:
calculate_weighted_cos_dist(5,0)

0.6666666666666667
0.40824829046386296
0.0
------------------------------------------------------------------------------------------------------------------------
Weighted value:
A    0
B    0
C    0
Name: 5, dtype: int64


In [18]:
calculate_weighted_cos_dist(5, 0.5)

0.7216878364870323
0.6666666666666667
0.2886751345948129
------------------------------------------------------------------------------------------------------------------------
Weighted value:
A    1.0
B    3.0
C    1.0
Name: 5, dtype: float64


In [19]:
calculate_weighted_cos_dist(5, 1)

0.8473185457363233
0.8498365855987975
0.6172133998483676
------------------------------------------------------------------------------------------------------------------------
Weighted value:
A    2
B    6
C    2
Name: 5, dtype: int64


In [20]:
calculate_weighted_cos_dist(5, 2)

0.9460945407607455
0.9525793444156805
0.8651809126974003
------------------------------------------------------------------------------------------------------------------------
Weighted value:
A     4
B    12
C     4
Name: 5, dtype: int64


# Excercise 1c.

In [21]:
# Create initial array. 
D = np.array([2/7, 3/7, 6/7])

In [22]:
# Placeholder array for variables specified in second column.
# E = np.array([x, y, x])

In [23]:
# 2/7x + 3/7y + 6/7z = 0

In [24]:
# Multiply by GCF 7/1 to eliminate fraction
# 2/7 * 7/1 = 14/7 = 2
# 3/7 * 7/1 = 21/7 = 3
# 6/7 * 7/1 = 42/7 = 6

In [25]:
# Re-write equation with newly simplified integers:
# 2x + 3y + 6z = 0

In [26]:
# Isolate 'z':
# 6z = 2x + 3y
# Divide/Multiply by inverse of 6 (1/6) to eliminate variable 'z.'
# z = -1/3x - 2/3y

In [27]:
# Append value of z to existing array 'E.'
# E = np.array([x, y,(-1/3x - 2/3y)])

In [28]:
# Use values of x and y to solve for z.
# x = 1
# y = 0

In [29]:
# z = -1/3(1) - 2/3(0)
# z = -1/3 - 0
# z = -1/3

In [30]:
# Manually normalize vector
# 1^2 + 0^2 + (-1/3)^2 = 
# square root(1 + 1/9)
# Assign value to variable 'F.'

In [31]:
# Manual calculation for orthonormal vector
# F * E

In [32]:
D = np.array([2/7, 3/7, 6/7])

In [33]:
# New array with value of z apended. 
E = np.array([1, 0, -1/3])

In [34]:
# Orthonormal vector value
F = 1/np.sqrt(1 + 1/9)

In [35]:
G = E * F 

In [36]:
# Print final array.
G

array([ 0.9486833 ,  0.        , -0.31622777])

# Excercise 1d. 

In [37]:
# Create initial array. 
mat_1 = np.array([[1, 1], [2, 2], [3, 4]])

In [38]:
# Find dot product of mat_1. 
mat_trans = np.dot(mat_1.transpose(), mat_1)
# Apply linear algebra function to find eigen vector. 
eigen_val, eigen_vec = lalg.eig(mat_trans)

In [39]:
# Output array. 
eigen_vec

array([[-0.77512996, -0.63180182],
       [ 0.63180182, -0.77512996]])

In [40]:
# Output final array. 
eigen_val

array([ 0.14344504+0.j, 34.85655496+0.j])

# Excercise 1e.

In [41]:
# Create numpy array of values. 
a_ray_1 = np.array([1,2,3])

In [42]:
# All vector dot products must equal 0

In [43]:
# If a_ray_2 = np.array([x,y,z]), by extension the following must be TRUE:

# a_ray_1 dot a_ray_2 = 
# (1,2,3) dot (1,1,z) =
# 1 + 2 +3z = 0
# Add non-variable integers to yield:
# 3 + 3z = 0
# Subtract 3 from both sides.
# 3z = -3
# Divide by 3, yielding:
# z = -1

In [44]:
# Add z to initialized array containing values: (1, 1).
a_ray_2 = np.array([1, 1, -1])

In [45]:
# Check to determine whether dot product of two arrays is equal to zero. 
np.dot(a_ray_1, a_ray_2)

0

# Excercise 1f. 

In [46]:
# Create array values. 
diag_mat_M = np.array([[1, 0, 0], [0, 2, 0], [0, 0, 0]])

In [47]:
# Use the Moore Pseudo inverse function on array diag_mat_M. 
# Produce output of array values.
np.linalg.pinv(diag_mat_M)

array([[1. , 0. , 0. ],
       [0. , 0.5, 0. ],
       [0. , 0. , 0. ]])

## Number 2: Excercise 11.3.2

In [48]:
# Initialize given array. 
M_val = np.array([[1,1,1,0,0], [3,3,3,0,0], [4,4,4,0,0], [5,5,5,0,0], [0,0,0,2,2]])
M_val

array([[1, 1, 1, 0, 0],
       [3, 3, 3, 0, 0],
       [4, 4, 4, 0, 0],
       [5, 5, 5, 0, 0],
       [0, 0, 0, 2, 2]])

In [49]:
# Array after initial calculations:
U_val = np.array([[.14, 0],[.42,0], [.56,0], [.70,0], [0,.60], [0, .75], [0, .30]])
U_val

array([[0.14, 0.  ],
       [0.42, 0.  ],
       [0.56, 0.  ],
       [0.7 , 0.  ],
       [0.  , 0.6 ],
       [0.  , 0.75],
       [0.  , 0.3 ]])

In [50]:
# Values of sigma.
sigma_val = np.array([[12.4, 0],[0,9.5]])
sigma_val

array([[12.4,  0. ],
       [ 0. ,  9.5]])

In [51]:
# Applying vectorized operation to array. 
VT_val=np.array([[.58,.58,.58,0,0],[0,0,0,.71,.71]])
VT_val

array([[0.58, 0.58, 0.58, 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.71, 0.71]])

In [52]:
# Create final array for Leslie's picks. 
Leslie_picks = np.array([[1,1,1,0,0],[3,3,3,0,0],[4,4,4,0,0],[5,5,5,0,0],[0,0,0,4,4],[0,0,0,5,5],[0,0,0,2,2],[0,3,0,0,4]])
Leslie_picks

array([[1, 1, 1, 0, 0],
       [3, 3, 3, 0, 0],
       [4, 4, 4, 0, 0],
       [5, 5, 5, 0, 0],
       [0, 0, 0, 4, 4],
       [0, 0, 0, 5, 5],
       [0, 0, 0, 2, 2],
       [0, 3, 0, 0, 4]])

In [53]:
# Find concept space for Leslie's picks. 
Leslie_concept_space = np.array([0,3,0,0,4])

In [54]:
# Dot product of Leslie concept space and v^t. 
Leslie_rating = np.dot(Leslie_concept_space,VT_val.T)
Leslie_rating

array([1.74, 2.84])

In [55]:
# Dot product for Leslie rating and v^t values. 
alternate_picks = np.dot(Leslie_rating, VT_val)
alternate_picks

array([1.0092, 1.0092, 1.0092, 2.0164, 2.0164])

In [56]:
# Leslie's rating history indicates that they are more likely to prefer romantic movies over any other genre. 